version: '2'
services:
  app:
    build: .
    working_dir: /go
    command: "dev_appserver.py ./src/${BUILD_TARGET}/app.yaml --host 0.0.0.0 --port=8080 --admin_host 0.0.0.0 --admin_port=8000 --skip_sdk_update_check"
    ports:
      - $PORT:8080
      - $ADMIN_PORT:8000
    volumes:
      - .:/go
      - ./gcloud:/root/.config/gcloud
  dep:
    image: instrumentisto/dep:0.3.2
    working_dir: /go/src/${BUILD_TARGET}
    command: dep init
    volumes:
      - ./src/${BUILD_TARGET}:/go/src/${BUILD_TARGET}
