runtime: go
api_version: go1.8

handlers:
- url: /.*
  script: _go_app
  secure: optional

automatic_scaling:
  max_concurrent_requests: 40
  min_idle_instances: 0
  max_idle_instances: 1

includes:
  # TODO
  # cp ./secret.sample.yaml ./secret.yaml
  # and modify your access keys
  - secret.yaml

nobuild_files:
  - vendor

skip_files:
  - \.gitignore
  - \.DS_StoreY
  - \.envrc
  - README.md
  - ^.*\.yaml
  - \.git/.*
  - ^\.idea/.*
  - ^.*\.iml
  - Gopkg.*
  - vendor
  - test
